### PR TITLE
fix(segmentation): List surface representations in the segmentation table for 3D views.

### LINKED ISSUE #5651: [Bug] Segments missing when changing to 3D layout
### Describe the Bug

Segments are no longer available in the side panel when switching from a common to a 3D layout. The 3D viewport has the jump errors which if used produce an error 

### Steps to Reproduce

1. Display https://viewer-dev.ohif.org/segmentation?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5
2. Add segments on viewport 2
3. Switch to 3D main 

https://github.com/user-attachments/assets/0257516d-b1bb-4871-a7b0-815c156b0e6d

### The current behavior

- Segments are missing from the side panel 
- Jump arrows are available but produce an error if used

### The expected behavior

Segments are available in the side panel
Jump errors move to each segment with no errors 

### System Information

  System:
    OS: Windows 11 10.0.26100
    CPU: (14) x64 Intel(R) Core(TM) Ultra 7 265U
    Memory: 6.41 GB / 31.46 GB
  Browsers:
    Chrome: 143.0.7499.110
    Edge: Chromium (140.0.3485.54)

### PR DESCRIPTION
**Pull request by jbocce**
### Context
Fixes #5651 

### Changes & Results
List surface representations in the segmentation table for 3D views. This was done by using an array of representation types instead of a single type for a panel. The first element of the array is the primary type of the panel, and the rest are secondary types that can also be displayed in the panel.

### Testing
See #5651.  

In general, only label maps will be viewable as surfaces in 3D viewports. So some simple steps to test are...
1. Launch a study.
2. Add a label map segmentation.
3. Use the brush tool to add a circle or sphere.
4. Switch to a view that contains 3D.
5. The label map side panel should list the label maps (that were converted to surfaces).
6. Most tools and functions should not be available but some functions will be such as hide/show segments, remove/remove segmentation. In general the feature set availability should be consistent with what existed in https://viewer.ohif.org/ for this scenario.
7. There should be no arrows to navigate the segments in the top-right of the viewport.
8. Clicking a segment should do nothing (i.e. no navigation via a segment click).

A bit of regression testing around both the label map and contour panels is necessary because the fix touched a few of the panel components. Best to try various functions and tools in each panel.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

  System:
    OS: Windows 11 10.0.26200
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 5.92 GB / 31.68 GB
  Binaries:
    Node: 20.9.0 - C:\Users\joebo\AppData\Local\fnm_multishells\33444_1767618650410\node.EXE
    Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.1.0 - C:\Users\joebo\AppData\Local\fnm_multishells\33444_1767618650410\npm.CMD
    bun: 1.2.23 - C:\Users\joebo\.bun\bin\bun.EXE
  Browsers:
    Chrome: 143.0.7499.170

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by jbocce** [comment]
> Let's add a test in playwright (no screenshots) target the element and see it has some values in the segments

Will do for sure.

**Comment by jbocce** [comment]
> There is a toast message when clicking on the individual segments
> 
> 1. Display https://deploy-preview-5700--ohif-dev.netlify.app/segmentation?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5
> 2. Switch to 2x2 and add labelmap segments on series 2
> 3. Switch to 3D layout and select 3D series
> 4. Click segments
>    Result: Toast message is displayed
> 
> There is also a toast message when trying to add a contour segement
> 
> 1. Display https://deploy-preview-5700--ohif-dev.netlify.app/segmentation?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5
> 2. Switch to 2x2 and add labelmap segments on series 2
> 3. Switch to 3D layout, select an MPR series
> 4. Switch to contours tab and click add segment
>    Result:
>    Error message displayed

The fix for the first is in OHIF. However the second will be handled by a change in cornerstone namely: https://github.com/cornerstonejs/cornerstone3D/pull/2552

File: tests/pages/RightPanelPageObject.ts [hunk 1]
```diff
@@ -115,15 +115,15 @@ export class RightPanelPageObject {
     const getSegmentationByText = (text: string) => this.getPanelRowByText(text);
 
     return {
-      getSegmentationCount: async () => {
+      getSegmentCount: async () => {
```
Comment (jbocce) [inline tests/pages/RightPanelPageObject.ts:118]: These were misnamed so I corrected them.

File: extensions/cornerstone/src/panels/PanelSegmentation.tsx [hunk 2]
```diff
@@ -21,13 +21,14 @@ import {
 type PanelSegmentationProps = {
   children?: React.ReactNode;
 
-  // The representation type for this segmentation panel. Undefined means all types.
-  segmentationRepresentationType?: SegmentationRepresentations;
+  // The representation types for this segmentation panel. Undefined means all types.
+  // The first element is the primary type. Additional elements are secondary types.
```
Comment (sedghi) [inline extensions/cornerstone/src/panels/PanelSegmentation.tsx:25]: if it requires migrations, let's add it to docs

**Review by sedghi — APPROVED** [review]

File: extensions/cornerstone/src/panels/PanelSegmentation.tsx (hunk 2 above)
Comment (jbocce) [reply extensions/cornerstone/src/panels/PanelSegmentation.tsx:25]: No it does not require migration. The type was just added in 3.12 for the contour tab.
