### PR TITLE
BUG: Fix changing colormap for second volume in fusion viewport

### LINKED ISSUE #4744: [Bug] Colormap cannot be changed for the second volume in a VolumeViewport
### Describe the Bug

When changing the colormap for the second volume, this always gets applied to the first volume. This is due to a bug in cornerstone extension commandsModule.ts, setViewportColormap. To set the colormap on a viewport, it requires the volumeId. Currently this is retrieved by `viewport.getVolumeId()`, which only returns the first volumeId.

It could be changed by adding a specifier, i.e. `viewport.getVolumeId({ volumeId: <volumeId> })`, but this requires the volumeId to update to be known or retrievable. In this function, the correct volume is identified by the DisplaySetInstanceUID, which is slightly different from the volumeId, and therefore cannot be directly used to get the correct volumeId.

### Steps to Reproduce

1. Load the [PET-data case](https://viewer.ohif.org/tmtv?StudyInstanceUIDs=1.2.840.113619.2.290.3.3767434740.838.1526468636.966) in OHIF viewer.
2. Try to change the colormap on the PT volume in a fusion viewport. This applies the selected colormap  to the CT volume (which is the first volume in the viewport)

### The current behavior

Colormaps can only be changed for the first volume in a viewport.

### The expected behavior

Selecting the second volume in the actionmenu should apply the chosen colormap to the second volume in the viewport.

### OS

Linux 22.04.4 LTS

### Node version

20.11.0

### Browser

Chrome 122

### PR DESCRIPTION
**Pull request by JoostJM**
### Context

Fixes #4744.

When changing the colormap for the second volume, this always gets applied to the first volume. This is due to a bug in cornerstone extension commandsModule.ts, setViewportColormap. To set the colormap on a viewport, it requires the volumeId. Currently, this is retrieved by `viewport.getVolumeId()`, which only returns the first volumeId.

### Changes & Results

The event does pass the `displaySetInstanceUID`, which correctly identifies the volume. However, `volumeId` is slightly different (in this use case, prefixed by "CornerstoneStreamingVolume:". Implement a fix where all volumeIds in the viewport are filtered by comparing it to the displaySetInstanceUID. If a match is found (i.e. volumeId containing the displaySetInstanceUID), use that volumeId. Otherwise, use the first volumeId.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] (N/A) The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS:  Linux 22.04.4
- [x] Node version:  20.11.0
- [x] Browser: Chrome 122.0.6261.94
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: extensions/cornerstone/src/commandsModule.ts [hunk 1]
```diff
@@ -739,7 +739,12 @@ function commandsModule({
           displaySetInstanceUID = viewports.get(viewportId)?.displaySetInstanceUIDs[0];
         }
 
-        const volumeId = viewport.getVolumeId();
+        // ToDo: Find a better way of obtaining the volumeId that corresponds to the displaySetInstanceUID
+        const volumeId =
+          viewport
+            .getAllVolumeIds()
+            .find((_volumeId: string) => _volumeId.includes(displaySetInstanceUID)) ??
+          viewport.getVolumeId();
```
Comment (sedghi) [inline extensions/cornerstone/src/commandsModule.ts:747]: This is the correct way, you can remove Todo

**Review by sedghi — APPROVED** [review]
