### PR TITLE
fix(dicom overlay): Handle special cases of ArrayBuffer for various DICOM overlay attributes.

### LINKED ISSUE #3672: [Bug] DICOM Overlay does not work on Local
### Describe the Bug

Drag and drop a DICOM overlay in local and see it does not work

[Archive.zip](https://github.com/OHIF/Viewers/files/12702484/Archive.zip)

### Steps to Reproduce

Drag and drop it in the viewer-dev.ohif.org/localbasic

### The current behavior

Shows nothing

### The expected behavior

Should show the grid on them		

### OS

mac

### Node version

18

### Browser

Chrome

### PR DESCRIPTION
**Pull request by jbocce**
### Context

Fixes #3672

### Changes & Results

Check for ArrayBuffer values in the metadata for pixelData, columns, rows, and origin.

### Testing

Follow steps in #3672

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS: Windows 11
- [x] Node version: 18.16.1
- [x] Browser: Chrome 117.0.5938.92
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: platform/core/src/classes/MetadataProvider.ts [hunk 1]
```diff
@@ -291,12 +290,39 @@ class MetadataProvider {
           const ROIStandardDeviationTag = `${groupStr}1303`;
           const OverlayOrigin = instance[OverlayOriginTag];
 
+          let rows = 0;
+          if (instance[OverlayRowsTag] instanceof Array) {
+            const rowsInt16Array = new Uint16Array(instance[OverlayRowsTag][0]);
```
Comment (sedghi) [inline platform/core/src/classes/MetadataProvider.ts:295]: why uint16? requires a comment at least

File: platform/core/src/classes/MetadataProvider.ts [hunk 2]
```diff
@@ -291,12 +290,39 @@ class MetadataProvider {
...
+            const columnsInt16Array = new Uint16Array(instance[OverlayColumnsTag][0]);
+            columns = columnsInt16Array[0];
+          } else {
+            columns = instance[OverlayColumnsTag];
+          }
+
+          let x = 0;
+          let y = 0;
+          if (OverlayOrigin.length === 1) {
+            const originInt16Array = new Int16Array(OverlayOrigin[0]);
```
Comment (sedghi) [inline platform/core/src/classes/MetadataProvider.ts:312]: ditto

**Review by sedghi — COMMENTED** [review]
see my comment, thanks

**Review by sedghi — APPROVED** [review]
