### PR TITLE
Bug: Fix segmentationid undefined 5106

### LINKED ISSUE #5106: [Bug] TypeError: Cannot Read Properties of Undefined (reading 'segmentationId') in addNewSegment
### Describe the Bug

When I press the hotkey "A," which is used to add a new segment, in a viewport with no active segmentation, the application throws a TypeError: "Cannot read properties of undefined (reading 'segmentationId')".

https://github.com/user-attachments/assets/2fb0ad54-191f-4347-adf1-fff41b919d7c

### Steps to Reproduce

1. Open the OHIF viewer and load an image in a viewport.

2. Ensure that there is no active segmentation in the selected viewport.

3. Press the hotkey "A" (the shortcut to add a new segment).

4. Observe that the application throws a TypeError: "Cannot read properties of undefined (reading 'segmentationId')" in the NavigationComponent.

### The current behavior

When the hotkey "A" is pressed in a viewport with no active segmentation, the application immediately throws a TypeError: "Cannot read properties of undefined (reading 'segmentationId')".

### The expected behavior

When the hotkey "A" is pressed in a viewport with no active segmentation, the application should handle the situation with proper error handling.

### OS

Windows 11

### Node version

20.18.1

### Browser

Chrome 137.0.7151.69

### PR DESCRIPTION
**Pull request by vishnusureshperumbavoor**
### Context

Fixes #5106 

When pressing the hotkey "A" to add a new segment in a viewport with no active segmentation, the application previously threw a TypeError:

```
Cannot read properties of undefined (reading 'segmentationId')
```

#### Root Cause 
The code attempted to access segmentationId on an undefined segmentation object when no segmentation was active.

### Changes & Results

Implemented graceful handling for missing active segmentation:

* Added null check for activeSegmentation.

* Added warning log to inform developers of the missing segmentation.

* Prevented execution of addSegment when no active segmentation is present, avoiding the TypeError

Before: Pressing "A" with no active segmentation caused a TypeError and crashed the workflow.

After: Pressing "A" with no active segmentation logs a warning and safely exits, keeping the application stable.

### Testing

1. Open the OHIF viewer and load any image in a viewport.

2. Ensure there is no active segmentation in the selected viewport.

3. Press the hotkey "A".

4. Confirm that a warning is logged and no error is thrown.

#### PR

- [X] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [X] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [X] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [X] OS: Windows 11
- [X] Node version: 20.18.1
- [X] Browser: Chrome 137

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: extensions/cornerstone/src/commandsModule.ts [hunk 1]
```diff
@@ -1874,6 +1874,9 @@ function commandsModule({
       const { segmentationService } = servicesManager.services;
       const { activeViewportId } = viewportGridService.getState();
       const activeSegmentation = segmentationService.getActiveSegmentation(activeViewportId);
+      if (!activeSegmentation) {
+        console.warn('No active segmentation found for viewport:', activeViewportId);
```
Comment (sedghi) [inline extensions/cornerstone/src/commandsModule.ts]: i don't see how a console warn fix your issue, hmmmm, you meant to return?

Comment (vishnusureshperumbavoor) [reply extensions/cornerstone/src/commandsModule.ts]: Changed to return
