### PR TITLE
fix(jump-to-contour-segment): For contours like those from RSTRUCTs, use generic jumpToSegmentCenter if a segment center is available.

### LINKED ISSUE #5783: [Bug] Jump segment broken for RTSTRUCT
### Describe the Bug

Regression within 3.12. 

### Steps to Reproduce

1. Display a study with RTSTRUCT e.g. https://viewer-dev.ohif.org/segmentation?StudyInstanceUIDs=1.3.6.1.4.1.32722.99.99.239341353911714368772597187099978969331
2. Load RTSTRUCT 
3. Click segment or use arrows to jump segment 

### The current behavior

Nothing happens 

### The expected behavior

The arrows and segment should navigate to the correct image with the segment 

### System Information

  System:
    OS: Windows 11 10.0.26100
    CPU: (14) x64 Intel(R) Core(TM) Ultra 7 265U
    Memory: 13.25 GB / 31.46 GB
  Browsers:
    Chrome: 144.0.7559.110
    Edge: Chromium (140.0.3485.54)

### PR DESCRIPTION
**Pull request by jbocce**
### Context
Fixes #5783

### Changes & Results
Use the jumpToCenter method for contours if the contour has a center calculated. 

### Testing
See #5783 

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment
  System:
    OS: Windows 11 10.0.26200
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 9.11 GB / 31.68 GB
  Binaries:
    Node: 22.17.0 - C:\Users\joebo\AppData\Local\fnm_multishells\29608_1770221529011\node.EXE
    Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 11.6.2 - C:\Users\joebo\AppData\Local\fnm_multishells\29608_1770221529011\npm.CMD
    bun: 1.2.23 - C:\Users\joebo\.bun\bin\bun.EXE
  Browsers:
    Chrome: 144.0.7559.110

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

<h2>Greptile Overview</h2>

<h3>Greptile Summary</h3>

This PR improves navigation behavior for contour segmentations (like RTSTRUCT data) by enabling the use of `jumpToSegmentCenter` when a segment center is available.

## Key Changes
- Modified `jumpToSegmentNext` to check if contour segments have a calculated center before falling back to slice-by-slice navigation
- Added optional `center` parameter to `jumpToSegmentCenter` to accept pre-calculated centers, avoiding redundant center calculations
- Removed unused `viewRef` variable in the contour navigation loop
- The logic now follows: for contours, try to use center-based jump if center exists, otherwise fall back to slice-by-slice navigation

## Impact
- Provides smoother navigation for RTSTRUCT contours that have center coordinates in their cached stats
- Maintains backward compatibility with contours that don't have centers by keeping the existing slice navigation fallback
- Reduces code duplication by reusing the `jumpToSegmentCenter` method instead of only using it for labelmaps

<h3>Confidence Score: 4/5</h3>

- This PR is safe to merge with minimal risk - it's a focused bug fix that enhances existing functionality
- The changes are well-contained and follow good practices: adds optional parameter with default fallback, maintains backward compatibility, and improves UX for contours with centers. Only minor typo found in pre-existing JSDoc comment.
- No files require special attention

<details><summary><h3>Important Files Changed</h3></summary>

| Filename | Overview |
|----------|----------|
| extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts | Enhanced `jumpToSegmentNext` to use `jumpToSegmentCenter` for contours when a center is available, avoiding fallback to slice-by-slice navigation |

</details>

</details>

<h3>Sequence Diagram</h3>

```mermaid
sequenceDiagram
    participant Client
    participant jumpToSegmentNext
    participant _getSegmentCenter
    participant jumpToSegmentCenter
    participant ContourSliceLogic

    Client->>jumpToSegmentNext: Call with segmentationId, segmentIndex
    jumpToSegmentNext->>jumpToSegmentNext: Get representation type
    
    alt Type is CONTOUR
        jumpToSegmentNext->>_getSegmentCenter: Check if center exists
        _getSegmentCenter-->>jumpToSegmentNext: Return center or undefined
        
        alt Center exists (e.g., RTSTRUCT)
            jumpToSegmentNext->>jumpToSegmentCenter: Use center-based jump with center param
            jumpToSegmentCenter->>jumpToSegmentCenter: Jump viewport to world coordinates
            jumpToSegmentCenter-->>Client: Success
        else Center does not exist
            jumpToSegmentNext->>ContourSliceLogic: Use slice-by-slice navigation
            ContourSliceLogic->>ContourSliceLogic: Find nearest slice with contour
            ContourSliceLogic-->>Client: Navigate to slice
        end
    else Type is LABELMAP or SURFACE
        jumpToSegmentNext->>jumpToSegmentCenter: Use center-based jump (no center param)
        jumpToSegmentCenter->>_getSegmentCenter: Calculate center
        jumpToSegmentCenter->>jumpToSegmentCenter: Jump viewport to world coordinates
        jumpToSegmentCenter-->>Client: Success
    end
```

<sub>(3/5) Reply to the agent's comments like "Can you suggest a fix for this @greptileai?" or ask follow-up questions!</sub>

### CODE REVIEW

File: extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts [hunk 1]
```diff
@@ -1368,8 +1368,11 @@ class SegmentationService extends PubSubService {
       const representation = representations[0];
       const { type } = representation;
 
-      // For labelmaps, use the existing jumpToSegmentCenter method
-      if (type !== CONTOUR) {
+      // For contours, check if we have a segment center.
+      const center =
+        type === CONTOUR ? this._getSegmentCenter(segmentationId, segmentIndex) : undefined;
+      const canUseSegmentCenter = type !== CONTOUR || !!center;
```
Comment (wayfarer3130) [inline extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts:1374]: Technically, canUseSegmentCenter is only true if !!center - it has nothing to do with contour as the labelmaps can also lack a center if the statistics haven't yet computed.

Comment (jbocce) [reply extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts:1374]: What do you suggest then?

Comment (wayfarer3130) [reply extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts:1374]: lets leave it the way it is now given that it is tested.  We can update the hole file when the next steps are updated.

**Review by wayfarer3130 — APPROVED** [review]
