### PR TITLE
fix: set SR in ActiveViewport by clicking thumb

### LINKED ISSUE #1076: Unable to set SR in `ActiveViewport` by clicking thumbnail
You can click a thumbnail to set it as the dataSet for the activeViewport; however, we get odd results if we **click** an SR thumbnail.

CYUL2Q7noe

### PR DESCRIPTION
**Pull request by rodrigolabs**
Fixes #1076 

---

## Preview 

ezgif com-optimize

### CODE REVIEW

File: platform/core/src/redux/reducers/viewports.js [hunk 1]
```diff
@@ -85,14 +84,24 @@ const viewports = (state = defaultState, action) => {
...
         ? state.activeViewportIndex
         : action.viewportIndex;
-      currentData = cloneDeep(state.viewportSpecificData[viewportIndex]) || {};
+      const { dom } = state.viewportSpecificData[viewportIndex];
+
       viewportSpecificData = cloneDeep(state.viewportSpecificData);
-      viewportSpecificData[viewportIndex] = merge({}, currentData, action.data);
+      viewportSpecificData[viewportIndex] = {
+        dom,
+        ...action.data,
```
Comment (dannyrb) [inline platform/core/src/redux/reducers/viewports.js]: I know that `action.data` is everything, but what is `action.data`?
Can we be more explicit here? Or are we SOL with the current setup?

File: platform/viewer/src/connectedComponents/Viewer.js [hunk 2]
```diff
@@ -295,7 +295,10 @@ class Viewer extends Component {
                 activeIndex={this.props.activeViewportIndex}
               />
             ) : (
-              <ConnectedStudyBrowser studies={this.state.thumbnails} />
+              <ConnectedStudyBrowser
+                studies={this.state.thumbnails}
+                studyMetadata={this.props.studies}
```
Comment (dannyrb) [inline platform/viewer/src/connectedComponents/Viewer.js]: Man, we really need to knock out a better way to do this

File: platform/core/src/redux/reducers/viewports.js (hunk 1 above)
Comment (rodrigolabs) [reply platform/core/src/redux/reducers/viewports.js]: This is what we're calling `viewportSpecificData`, e.g.:
```javascript
{
  displaySetInstanceUid,
  seriesDate,
  seriesTime,
  seriesInstanceUid,
  seriesNumber,
  plugin,
  seriesDescription,
  modality,
  [etc...]
}
```

Comment (dannyrb) [reply platform/core/src/redux/reducers/viewports.js]: Right, but we need to start destructuring "data" so it's clearer at a glance what's going into reactive state, and to make sure nothing new sneaks in unless we deliberately add it.

File: platform/viewer/src/connectedComponents/Viewer.js (hunk 2 above)
Comment (rodrigolabs) [reply platform/viewer/src/connectedComponents/Viewer.js]: Totally agree! In the next steps, we can probably add the study list in the redux store to avoid that.
