### PR TITLE
fix(calibration): No calibration popup caused by perhaps an unused code optimization for production builds

### LINKED ISSUE #3724: [Bug] No popup after drawing calibration line on viewer-dev.ohif.org
### Describe the Bug

After drawing the line for the calibration tool, no popup is displayed to prompt for the length of the line drawn. However this is only occurs with the demo servers viewer-dev.ohif.org and viewer.ohif.org. Using localhost:3000 the tool works correctly.

### Steps to Reproduce

1. Navigate to one of the demo servers
2. View a study.
3. Select the calibration tool and draw a line.

### The current behavior

No popup prompting for the length of the line drawn.

### The expected behavior

Popup prompting for the length of the line drawn.

### OS

Windows 11

### Node version

18.16.1

### Browser

Chrome 117.0.5938.152

### PR DESCRIPTION
**Pull request by jbocce**
Removed unused code that might have been optimized for production builds which in turn caused an exception to skip the popup prompt.

### Context
 Fixes #3724 

### Changes & Results

Removed unused code that might have been optimized for production builds which in turn caused an exception to skip the popup prompt.

### Testing

See #3724

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS: Windows 11
- [x] Node version: 18.16.1
- [x] Browser: Chrome 118.0.5993.71
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: extensions/cornerstone/src/tools/CalibrationLineTool.ts [hunk 1]
```diff
@@ -66,14 +66,6 @@ export function onCompletedCalibrationLine(servicesManager, csToolsEvent) {
       calculateLength3(annotationData.handles.points[0], annotationData.handles.points[1]) * 100
     ) / 100;
 
-  // calculate the currently applied pixel spacing on the viewport
```
Comment (jbocce) [inline extensions/cornerstone/src/tools/CalibrationLineTool.ts:69]: This code was unused and throwing an exception for production builds.

**Review by sedghi — APPROVED** [review]
