### PR TITLE
[OHI-1357] feat(static-wado): add support for case-insensitive searching

### LINKED ISSUE #4522: [Bug] How to modify a configuration file to make case insensitive when searching？
### Describe the Bug

V 3.9.1
I want to search by name, but it seems to be case sensitive when searching. How can I modify the configuration file to ignore case when searching?
I tried to modify the configuration file, but it didn't work。I changed qidoSupportsIncludeField and supportsFuzzyMatching to true. It didn't work

namespace: '@ohif/extension-default.dataSourcesModule.dicomweb',
      sourceName: 'dicomweb',
      configuration: {
        friendlyName: 'AWS S3 Static wado server',
        name: 'aws',
        wadoUriRoot: '****',
        qidoRoot: '*****',
        wadoRoot: '*****',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
        supportsWildcard: true,
        staticWado: true,
        singlepart: 'bulkdata,video',
        // whether the data source should use retrieveBulkData to grab metadata,
        // and in case of relative path, what would it be relative to, options
        // are in the series level or study level (some servers like series some study)
        bulkDataURI: {
          enabled: true,
          relativeResolution: 'studies',
          transform: url => url.replace('/pixeldata.mp4', '/rendered'),
        },
        omitQuotationForMultipartRequest: true,

### Steps to Reproduce

1、Enter the all lowercase name in the search box
2、The result will not display the same patient name with uppercase letters

### The current behavior

The result will not display the same patient name with uppercase letters

### The expected behavior

Distinguish case when searching

### OS

Win10

### Node version

v20.15.1

### Browser

Chrome

### PR DESCRIPTION
**Pull request by IbrahimCSAE**
### Context

This adds the option to filter static-wado results without being case-sensitive. You need to set the `caseSensitive` property on your static wado `dataSource` to `false`, the default is `true`.

Orthanc and other sources support case insensitive searching already.

Fixes OHI-1357
Close #4522

### CODE REVIEW

File: platform/app/public/config/default.js [hunk 1]
```diff
@@ -52,6 +52,7 @@ window.config = {
         supportsFuzzyMatching: false,
         supportsWildcard: true,
         staticWado: true,
+        caseSensitive: false,
```
Comment (sedghi) [inline platform/app/public/config/default.js:55]: Can you add it to the docs as well?

https://docs.ohif.org/configuration/configurationFiles

It would be useful to have this per query, so that the patient name search is case-insensitive, but other searches are not. Can you make this an object with keys?

**Review by sedghi — COMMENTED** [review]
we should make it per qido call and not global

**Comment by sedghi** [comment]
Can you try it in Orthanc too please?

**Comment by IbrahimCSAE** [comment]
> Can you try it in Orthanc too please?

I did, it works fine

**Review by sedghi — APPROVED** [review]

**Comment by sedghi** [comment]
@wayfarer3130 can you take a look at this please

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 2]
```diff
@@ -156,19 +164,28 @@ export default class StaticWadoClient extends api.DICOMwebClient {
...
     }
     if (actual?.Alphabetic) {
       actual = actual.Alphabetic;
     }
     if (typeof actual == 'string') {
+      if (!caseSensitive) {
+        if (typeof desired === 'string') {
+          desired = desired.toLowerCase();
+        }
+        if (typeof actual === 'string') {
```
Comment (wayfarer3130) [inline extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:185]: actual.toLowerCase is sufficient, and resolves one bug where === 'string' doesn't work correctly.

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 3]
```diff
@@ -227,7 +245,7 @@ export default class StaticWadoClient extends api.DICOMwebClient {
       return this.compareDateRange(testValue, valueElem.Value[0]);
     }
     const value = valueElem.Value;
```
Comment (wayfarer3130) [inline extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:247]: You can do the testValue.toLowerCase here instead.

File: platform/docs/docs/configuration/configurationFiles.md [hunk 4]
```diff
@@ -193,6 +193,12 @@ if auth headers are used, a preflight request is required.
 - `activateViewportBeforeInteraction`: (default to true), if set to false, tools can be used directly without the need to click and activate the viewport.
 - `autoPlayCine`: (default to false), if set to true, data sets with the DICOM frame time tag (i.e. (0018,1063)) will auto play when displayed
 - `addWindowLevelActionMenu`: (default to true), if set to false, the window level action menu item is NOT added to the viewport action corners
+- `caseSensitive`: an object with filter keys that should be case sensitive. By default, all filters are case sensitive. If you want to set a filter to be case insensitive, you can set it to false. Example:
```
Comment (wayfarer3130) [inline platform/docs/docs/configuration/configurationFiles.md:196]: You need to add a note that this only works for static DICOMweb query back ends

**Review by wayfarer3130 — CHANGES_REQUESTED** [review]
Just a couple of small changes.

**Comment by wayfarer3130** [comment]
Also, please change the default.js and e2e.js configurations to set this on by default - you may need to modify an integration test to support that.

**Comment by IbrahimCSAE** [comment]
> Just a couple of small changes.

thanks Bill, I'll do them as soon as I can

**Review by sedghi — COMMENTED** [review]
wait a minute does this only work on static wado backends? what happened to orthanc testing? did you do it?

**Comment by IbrahimCSAE** [comment]
> wait a minute does this only work on static wado backends? what happened to orthanc testing? did you do it?

orthanc case sensitivity is server side, OHIF doesn’t control it

**Comment by sedghi** [comment]
I thought the filtering happens client side when we looked at the code

**Comment by IbrahimCSAE** [comment]
> I thought the filtering happens client side when we looked at the code

It only happens if it's a static wado datasource, otherwise it calls the super method, we don't control or filter anything there, so it's all up to backend (orthanc in this case) what to return

See here

https://github.com/dan-rukas/viewers/blob/a926b82a6231e54fc097335f9ccf6fd3079f1231/extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts#L102

```js
  async searchForStudies(options) {
    if (!this.staticWado) {
      return super.searchForStudies(options);
    }

    const searchResult = await super.searchForStudies(options);
    const { queryParams } = options;

    if (!queryParams) {
      return searchResult;
    }

    const lowerParams = this.toLowerParams(queryParams);
    const filtered = searchResult.filter(study => {
      for (const key of Object.keys(StaticWadoClient.studyFilterKeys)) {
        if (!this.filterItem(key, lowerParams, study, StaticWadoClient.studyFilterKeys)) {
          return false;
        }
      }
      return true;
    });
    return filtered;
  }
  ```

**Comment by sedghi** [comment]
I think the way forward is to add `fuzzyMatching` to our static wado, since that seems to be wildly supported by lots of dicom servers, see https://cloud.google.com/healthcare-api/docs/dicom#search_transaction `fuzzyMatching` section. 

Right now it is set in the config file as `supportsFuzzyMatching`:false 


**From the link** 
fuzzymatching: If set to true, fuzzy matching will be applied to the PatientName tag. Fuzzy matching will perform tokenization and normalization of both the value of PatientName in the query and the stored value. It will match if any search token is a prefix of any stored token. For example, if PatientName is "John^Doe", then "jo", "Do" and "John Doe" will all match. However "ohn" will not match.

**Comment by IbrahimCSAE** [comment]
> I think the way forward is to add `fuzzyMatching` to our static wado, since that seems to be wildly supported by lots of dicom servers, see https://cloud.google.com/healthcare-api/docs/dicom#search_transaction `fuzzyMatching` section.
> 
> Right now it is set in the config file as `supportsFuzzyMatching`:false
> 
> **From the link** fuzzymatching: If set to true, fuzzy matching will be applied to the PatientName tag. Fuzzy matching will perform tokenization and normalization of both the value of PatientName in the query and the stored value. It will match if any search token is a prefix of any stored token. For example, if PatientName is "John^Doe", then "jo", "Do" and "John Doe" will all match. However "ohn" will not match.

I implemented it according to the definition from GCP. please take another look now, thanks

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 5]
```diff
@@ -156,18 +156,36 @@
...
     if (Array.isArray(actual)) {
-      return actual.find(actualItem => this.compareValues(desired, actualItem));
+      return actual.find(actualItem => this.compareValues(desired, actualItem, fuzzyMatching));
     }
     if (actual?.Alphabetic) {
       actual = actual.Alphabetic;
     }
+
+    if (fuzzyMatching && typeof actual === 'string' && typeof desired === 'string') {
+      const normalizeValue = str => str.replace(/^\*+|\*+$/g, '').toLowerCase();
```
[the remark this answers is not in the document]
Comment (sedghi) [reply extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:174]: @IbrahimCSAE can you check this as well?

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 6]
```diff
@@ -156,18 +156,44 @@ export default class StaticWadoClient extends api.DICOMwebClient {
...
+        if (str.endsWith('*')) {
+          str = str.slice(0, -1);
+        }
+        return str.toLowerCase();
+      };
+
+      const normalizedDesired = normalizeValue(desired);
+      const normalizedActual = normalizeValue(actual);
+
+      const tokenizeAndNormalize = str => str.replace(/\^/g, ' ').split(/\s+/).filter(Boolean);
```
Comment (wayfarer3130) [inline extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:187]: This can be written:
 const tokenizeAndNormalize = str => str.split(/(\s|\^]+/).filter(Boolean);

**Review by sedghi — APPROVED** [review]
See Bill's comment and it is good to go thanks

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 7]
```diff
@@ -156,18 +156,44 @@ export default class StaticWadoClient extends api.DICOMwebClient {
...
+
+      const desiredTokens = tokenizeAndNormalize(normalizedDesired);
+      const actualTokens = tokenizeAndNormalize(normalizedActual);
+
+      return desiredTokens.some(desiredToken =>
```
Comment (wayfarer3130) [inline extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:192]: This should be desiredTokens.every - I know that the GCP definition has it with any, but that doesn't make any sense because it should be possible to provide a list of values to support "any", while it is important to allow multiple values to be done using every - think of patients whose first name is "John", and we are looking for "John Smith"
If it is done with John Smith as the query field, then some will find all the johns AND all the smiths, not the john smiths.

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 8]
```diff
@@ -156,18 +156,44 @@ export default class StaticWadoClient extends api.DICOMwebClient {
...
-      return actual.find(actualItem => this.compareValues(desired, actualItem));
+      return actual.find(actualItem => this.compareValues(desired, actualItem, fuzzyMatching));
     }
     if (actual?.Alphabetic) {
       actual = actual.Alphabetic;
     }
+
+    if (fuzzyMatching && typeof actual === 'string' && typeof desired === 'string') {
+      const normalizeValue = str => {
+        if (str.startsWith('*')) {
```
Comment (wayfarer3130) [inline extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:175]: If you supported wildcard matching here too, with prefix/suffix, then you can support fuzzy matching for names, and wildcard start/ends with for other fields.  I would suggest changing the support of supportsWildcard to `suffix`, to automatically have the wildcard added only at the end, although doing a full contains works as well for client side matching.

File: platform/app/public/config/default.js [hunk 9]
```diff
@@ -50,7 +50,7 @@ window.config = {
         imageRendering: 'wadors',
         thumbnailRendering: 'wadors',
         enableStudyLazyLoad: true,
-        supportsFuzzyMatching: false,
+        supportsFuzzyMatching: true,
```
Comment (wayfarer3130) [inline platform/app/public/config/default.js:53]: Suggest changing the next line for supportsWildcard to false, or else implement the logic for wildcard matching too.

Comment (IbrahimCSAE) [reply platform/app/public/config/default.js:53]: done

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts (hunk 6 above)
Comment (IbrahimCSAE) [reply extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:187]: done

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 10]
```diff
@@ -156,18 +156,44 @@ export default class StaticWadoClient extends api.DICOMwebClient {
...
     if (Array.isArray(actual)) {
-      return actual.find(actualItem => this.compareValues(desired, actualItem));
+      return actual.find(actualItem => this.compareValues(desired, actualItem, fuzzyMatching));
     }
     if (actual?.Alphabetic) {
       actual = actual.Alphabetic;
     }
+
+    if (fuzzyMatching && typeof actual === 'string' && typeof desired === 'string') {
+      const normalizeValue = str => {
```
[the remark this answers is not in the document]
Comment (IbrahimCSAE) [reply extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:174]: done

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts (hunk 8 above)
Comment (IbrahimCSAE) [reply extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts]: I think this implementation is sufficient for now. We can dedicate more time to implementing proper server-side filtering logic for static wado using lamdas or something similar then we can avoid all of this in the frontend.

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 11]
```diff
@@ -211,6 +231,9 @@ export default class StaticWadoClient extends api.DICOMwebClient {
    * @returns
    */
   filterItem(key: string, queryParams, study, sourceFilterMap) {
+    const { supportsFuzzyMatching = false } = this.config;
+    const isPatientName = key === 'patientname';
```
Comment (wayfarer3130) [inline extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:235]: Could you make it key.indexof('name')!==-1 so that it works for other names as well?

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts [hunk 12]
```diff
@@ -227,7 +250,8 @@ export default class StaticWadoClient extends api.DICOMwebClient {
       return this.compareDateRange(testValue, valueElem.Value[0]);
     }
     const value = valueElem.Value;
-    return this.compareValues(testValue, value);
+
+    return this.compareValues(testValue, value, supportsFuzzyMatching && isPatientName);
```
Comment (wayfarer3130) [inline extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts:254]: Can you pass in an options object instead of a single key - that way we can add wildcard matching in the future without changing the API.

File: extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts (hunk 11 above)
Comment (IbrahimCSAE) [reply extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts]: done

**Review by wayfarer3130 — APPROVED** [review]

**Comment by andylinton** [comment]
This change seems to have broken patient search for me. Using DCM4CHEE PACS with supportsFuzzyMatching: true, and supportsWildcard: true. I tried adding caseSensitive: false but this didn't help. Whatever I try, searching the patient list by name gives no results.

**Comment by andylinton** [comment]
I set staticWado to false and the search issue was resolved, I can now search by patient name.
