### PR TITLE
fix(cine): prevent crash on second view/hydration of SR series 

### LINKED ISSUE #5634: [Bug] OHIF crashes on second view/hydration of SR series
### Describe the Bug

For a particular study, namely 1.3.6.1.4.1.14519.5.2.1.7310.5101.860473186348887719777907797922, a second view (i.e. either double click or drag-and-drop) of an SR series causes OHIF to crash with the following exception...

```
Uncaught TypeError: e.getAllVolumeIds is not a function
    at initCineService.ts:5:30
    at Ve (initCineService.ts:31:35)
    at Object.getSyncedViewports [as _getSyncedViewports] (initCineService.ts:52:12)
    at j.getSyncedViewports (CineService.ts:75:39)
    at CineProvider.tsx:23:39
    at Object.Mo [as useReducer] (react-dom.production.min.js:163:451)
    at t.useReducer (react.production.min.js:26:114)
    at PR (CineProvider.tsx:56:29)
    at go (react-dom.production.min.js:160:137)
    at _s (react-dom.production.min.js:196:258)
```

Note that this behaviour was only seen on this particular study and furthermore the crash can be reproduced in 3.11.1.

### Steps to Reproduce

1. View the study 1.3.6.1.4.1.14519.5.2.1.7310.5101.860473186348887719777907797922. (https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7310.5101.860473186348887719777907797922)
2. Hydrate the (only) SR series.
3. Use the measurements side panel to navigate to the various measurements.
4. Attempt to view the SR series again.

### The current behavior

OHIF crashes. Browser window goes completely black. Exception in the console.

### The expected behavior

No crash at the very least.

### System Information

  System:
    OS: Windows 11 10.0.26200
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 5.00 GB / 31.68 GB
  Binaries:
    Node: 23.9.0 - ~\AppData\Local\fnm_multishells\52784_1765830696412\node.EXE
    Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.9.2 - ~\AppData\Local\fnm_multishells\52784_1765830696412\npm.CMD
    bun: 1.2.23 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (140.0.3485.54)
    Internet Explorer: 11.0.26100.7309
    Chrome: 143.0.7499.41 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by GhadeerAlbattarni**
### Context

Fixes #5634 

When an SR series is viewed/opened for the second time (via double-click or drag-and-drop), it causes a crash with `TypeError: getAllVolumeIds is not a function` because the cine service assumes all viewports are volume viewports.

### Changes

- Added a guard in `initCineService.ts` to return early when `getAllVolumeIds` is not available.

## Results
 The viewer no longer crashes when you reopen the SR series

**Before:**  
Reopening an SR series causes OHIF to crash with `getAllVolumeIds is not a function`.

Screenshot 2026-01-17 at 9 54 05 AM

**After:**  
SR series can be reopened without causing any crash or errors.

### Testing

1. Open the study with `StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7310.5101.860473186348887719777907797922`
2. Hydrate the SR series.
3. Use the measurements panel to navigate between measurements.
4. Attempt to view the SR series again 
5. Verify no crash happens

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS: macOS 10.15.4
- [x] Node version: v22.12.0
- [x] Browser: Chrome 83.0.4103.116

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: extensions/cornerstone/src/initCineService.ts [hunk 1]
```diff
@@ -2,6 +2,11 @@ import { cache, Types } from '@cornerstonejs/core';
 import { utilities } from '@cornerstonejs/tools';
 
 function _getVolumeFromViewport(viewport: Types.IBaseVolumeViewport) {
+  // Handle non-volume viewports that don't have getAllVolumeIds
+  if (!viewport || !viewport.getAllVolumeIds) {
```
Comment (jbocce) [inline extensions/cornerstone/src/initCineService.ts]: Consider changing this to `if(!viewport?.getAllVolumeIds) {`

**Comment by jbocce** [comment]
Please update your branch with master. Thanks.

**Comment by GhadeerAlbattarni** [comment]
Sure, thanks for your comments!

**Comment by jbocce** [comment]
The changes to the OHIF docs look good.

**Review by aimee-ferreira — APPROVED** [review]
Verification has passed. On second hydration of the SR, the application does NOT crash.
New defect logged unrelated to this PR: https://github.com/OHIF/Viewers/issues/5798
