### PR TITLE
fix(measurement): fix for measurement jump is not switching series in 2DMPR

### LINKED ISSUE #4751: [Bug]  Measurement Selection Not Switching Series in 2D MPR View
### Describe the Bug

When an annotation is created in the first series, then the second series is loaded, clicking on the measurement of the first series in the measurement panel does not switch back to the corresponding series in the 2D MPR view.
It is also noted that if two series in a session have different FrameOfReferenceUID, the series switches as expected when clicking a measurement from the measurement panel

https://github.com/user-attachments/assets/f11806aa-8816-43c1-9108-0cb7d74b894a

### Steps to Reproduce

1. Launch a multi-series study with the same FrameOfReferenceUID.
2. Draw an annotation on the first series.
3. Navigate to MPR mode.
4. Drag and drop the second series into MPR mode.
5. Click on the annotation of the first series from the measurement panel.
6. Observe the viewport - the series does not switch back to the first series.

### The current behavior

The series is not switching; instead, the annotation appears as a dashed line in the currently loaded series

### The expected behavior

When clicking on a measurement, the corresponding series should load and navigate to the slice containing the annotation

### OS

Windows 11

### Node version

20

### Browser

Chrome

### PR DESCRIPTION
**Pull request by arul-trenser**
### Context

- Fixes #4751 
- It also fix the issue that, on common layout while clicking on tracked measurement of different series, the viewport will update the series for the measurement but the jump to slice is not working.
- This PR has been incorporated by [FlyWheel.io](https://flywheel.io/).

https://github.com/user-attachments/assets/1833f35f-1a2a-4477-9e22-fedcb940e3ea

### Changes & Results

- To fix issue #4751, Added checking whether the found viewport have measurement displaySetInstanceUID and referencedImageId in JUMP_TO_MEASUREMENT_VIEWPORT event.
- To fix issue 

 > on common layout while clicking on tracked measurement of different series, the viewport will update the series for the measurement but the jump to slice is not working
 
 _checkForCachedJumpToMeasurementEvents function has been called, if we have measurement during loadViewportData.

https://github.com/user-attachments/assets/046c062f-e174-49c0-8996-dbde717a1bcc

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS: Windows 11
- [x] Node version: 18.19.0
- [x] Browser:
   Chrome 131.0.6778.265

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by sedghi** [comment]
I'm not able to reproduce the bug in our master branch, are you sure it is happening here https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.2.840.113619.2.290.3.3767434740.226.1600859119.501

**Comment by arul-trenser** [comment]
@sedghi We are still able to reproduce the issues in [https://viewer-dev.ohif.org/ ](https://viewer-dev.ohif.org/ ). 

> on common layout while clicking on tracked measurement of different series, the viewport will update the series for the measurement but the jump to slice is not working.

Previous in v3.8, while clicking on measurement in measurement panel, the viewport will load corresponding series and navigates to corresponding slice.
Currently in master and in v3.9, while clicking on measurement in panel, on first click the viewport is loaded with corresponding series and on second click the navigation to corresponding slice is happening.

https://github.com/user-attachments/assets/dd2daf6e-76a7-42df-af46-be12e91aef08

Issue 2: https://github.com/OHIF/Viewers/issues/4751 is also reproduceable in current main.

https://github.com/user-attachments/assets/91959f36-ec6c-4e09-b8d6-4c3f3fcc1da5

File: extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx [hunk 1]
```diff
@@ -286,7 +285,13 @@ const OHIFCornerstoneViewport = React.memo(
         );
 
         if (measurement) {
-          cs3DTools.annotation.selection.setAnnotationSelected(measurement.uid);
+          _checkForCachedJumpToMeasurementEvents(
```
Comment (sedghi) [inline extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx:288]: Where did `setAnnotationSelected` go?

Comment (arul-trenser) [reply extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx:288]: The `setAnnotationSelected` function is invoked by `_jumpToMeasurement` https://github.com/OHIF/Viewers/blob/72d6e8d36e4720ff61a66acb857ff640f5714815/extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx#L527, which itself is called by `_checkForCachedJumpToMeasurementEvents` https://github.com/OHIF/Viewers/blob/72d6e8d36e4720ff61a66acb857ff640f5714815/extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx#L497.

**Comment by sedghi** [comment]
I tried this, this has a strange side effect 
Try on [here](https://deploy-preview-4779--ohif-dev.netlify.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5)

The hanging protocol when mounting the measurement series does NOT correctly place orientations for some reason

https://github.com/user-attachments/assets/55de71c0-85c3-41ad-a7b0-bc3535a49c02

**Comment by arul-trenser** [comment]
@sedghi  It appears that the root cause for the above scenario is https://github.com/OHIF/Viewers/blob/master/platform/app/src/components/ViewportGrid.tsx#L189-L190.

In JUMP_TO_MEASUREMENT_LAYOUT, the first viewport is selected to jump to that measurement. Instead, we should select the viewport with the to which the `ImageOrientationPatient` is most closely aligned.

**Comment by sedghi** [comment]
can you try it to fix it?

**Comment by arul-trenser** [comment]
@sedghi I have fixed the issue mentioned in [above comment](https://github.com/OHIF/Viewers/pull/4779#issuecomment-2694653106). Could you please look into it?

**Comment by sedghi** [comment]
I have created this PR https://github.com/OHIF/Viewers/pull/4867 which solves the issue, please double check

**Comment by arul-trenser** [comment]
> I have created this PR #4867 which solves the issue, please double check

@sedghi 
In PR #4779 we have resolved 3 issues
Issue 1: When an annotation is created in the first series, then the second series is loaded, clicking on the measurement of the first series in the measurement panel, the viewport will to switch corresponding series; however, the transition to the corresponding slice does not occur. 
Issue 2: #4751 
Issue 3: After resolving issue 2, we encountered a subsequent issue as noted in the [comment](https://github.com/OHIF/Viewers/pull/4779#issuecomment-2694653106).

In PR #4867, Issue 1 is partially fixed and other two are not fixed.
Issue 1: As part of PR #4867, When an annotation is created in the first series, then the second series is loaded, clicking on the measurement of the first series in the measurement panel, the viewport will to switch corresponding series and jump to the corresponding slice; however the specific annotation is not highlighted.

https://github.com/user-attachments/assets/fa856ae0-68bb-4966-a841-29b4b1075720

Issue 2: This issue is not fixed

https://github.com/user-attachments/assets/c46171de-f00f-4429-9c23-a20d5d39758d

Issue 3: As this is subsequent issue that occurs once the issue 2 (#4751) is resolved, we are not able to reproduce it in the PR #4867; however the root cause of this issue is while updating the series in the series; we consistently choose the first viewport instead of selecting the viewport that has the most closest alignment with the `ImageOrientationPatient`. This problem has been addressed in this PR; however it still persists in PR #4867.

**Comment by arul-trenser** [comment]
@sedghi  While checking this we found one more issue which is not handled in this PR also not resolved in #4867.
**Issue: With `disableConfirmationPrompts: true` config, the slice switch for annotation is not happening in MPR mode.** 
Steps to Reproduce:
1. Launch the study in viewer
2. Drag and drop the SR report
3. Switch to MPR mode
4. Now click on the measurement
We observe that slice jumping is not happening in MPR mode with `disableConfirmationPrompts: true` config.

https://github.com/user-attachments/assets/d2742247-0f5c-4155-adda-817ea1e6e276

**Comment by nithin-trenser** [comment]
> @sedghi While checking this we found one more issue which is not handled in this PR also not resolved in #4867. **Issue: With `disableConfirmationPrompts: true` config, the slice switch for annotation is not happening in MPR mode.** Steps to Reproduce:
> 
> 1. Launch the study in viewer
> 2. Drag and drop the SR report
> 3. Switch to MPR mode
> 4. Now click on the measurement
>    We observe that slice jumping is not happening in MPR mode with `disableConfirmationPrompts: true` config.
> 
>  MPR_SR_Jump_issue.mp4

@sedghi 

This issue occurs regardless of the `disableConfirmationPrompts` config. The issue arises when a measurement is added from a Structured Report, the `cameraFocalPoint` is absent from the measurement data. For a volume viewport, this value is used to set the camera position (Jump to slice) from [here](https://github.com/nithin-trenser/cornerstone3D/blob/main/packages/core/src/RenderingEngine/BaseVolumeViewport.ts#L751-L765).

When an annotation is drawn in viewport, the view reference is saved along with the metadata https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-sr/src/utils/hydrateStructuredReport.ts#L186-L211. However, when an annotation is added via the SR report, the view reference is not included with the annotation metadata (the view reference holds the `cameraFocalPoint`.   In this scenario, the annotation data is generated from [here](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-sr/src/utils/hydrateStructuredReport.ts#L186-L194).

**Comment by sedghi** [comment]
@nithin-trenser I've updated https://github.com/OHIF/Viewers/pull/4867 and addressed the issue using the `referenceViewable` APIs. Could you please check it out and see if any of the previously fixed bugs still persist?

**Comment by Devu-trenser** [comment]
> @nithin-trenser I've updated #4867 and addressed the issue using the `referenceViewable` APIs. Could you please check it out and see if any of the previously fixed bugs still persist?

@sedghi The previously reported bugs are not reproducible in [#4867](https://github.com/OHIF/Viewers/pull/4867). 

However, I have **identified a minor issue**: when clicking a measurement from another series in the measurement panel, the selected measurement is not initially highlighted. The series and slice transition as expected. A video is attached below
**Also the issue mentioned in [this comment](https://github.com/OHIF/Viewers/pull/4779#issuecomment-2733602616) is not resolved yet**. (This issue occurs regardless of the disableConfirmationPrompts config. )


Notes: 

1. The highlight appears after the second click
2. Reproducible in the MPR mode also

Steps to reproduce:

1. Launch a multi-series study
3. Draw an annotation on the first series.
4. Open the measurement panel.
5. Switch to any other series
6. Click on a measurement that drawn in the first series. 
7. The series and slice will switch correctly, but the measurement will not be highlighted in the viewport.

https://github.com/user-attachments/assets/d39c1e4b-b116-448e-80a4-18d8df63786d

**Comment by sedghi** [comment]
Ok i fixed everything, check it out

**Comment by arul-trenser** [comment]
@sedghi  The issue mentioned in the [comment](https://github.com/OHIF/Viewers/pull/4779#issuecomment-2753553505) is still reproducible in [in PR 4867](https://deploy-preview-4867--ohif-dev.netlify.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5). Also, the issue mention in the [comment](https://github.com/OHIF/Viewers/pull/4779#issuecomment-2733602616) is not fixed. I have attached the video for reference.

Issue 1: Highlight is not working on layout switch - This is fixed as part of #4779 PR
Steps to reproduce:
1. Launch a multi series study
2. Draw annotation for two different series and track them
3. On the measurement panel, click on the annotation that is not drawn for the series that is currently loaded in the viewport
4. Observe the viewport, Series is changed and slice switch also happening; however the annotation is not selected both in viewport and in measurement panel
5. For 2D MPR mode only Series is changed and slice switch is not happening.

Root cause: [Annotation selection](https://github.com/OHIF/Viewers/pull/4867/files#diff-f646a4a0577bed86941659617be4626dc01a64c4ceb204b6bed0e2e1baad59d8R454) has been handled only for `JUMP_TO_MEASUREMENT_VIEWPORT` and not handled for event `JUMP_TO_MEASUREMENT_LAYOUT`


https://github.com/user-attachments/assets/6aa895ca-432d-4a33-b8f8-1c116d0773eb


Issue 2: The slice switch for annotation is not happening in MPR mode. - This is not fixed as part of #4779 PR
Steps to Reproduce:

Launch the study in viewer
Drag and drop the SR report
Switch to MPR mode
Now click on the measurement

Root cause: when a measurement is added from a Structured Report, the `cameraFocalPoint` is absent from the measurement data. For a volume viewport, this value is used to set the camera position (Jump to slice) from [here](https://github.com/nithin-trenser/cornerstone3D/blob/main/packages/core/src/RenderingEngine/BaseVolumeViewport.ts#L751-L765).

When an annotation is drawn in viewport, the view reference is saved along with the metadata https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-sr/src/utils/hydrateStructuredReport.ts#L186-L211. However, when an annotation is added via the SR report, the view reference is not included with the annotation metadata (the view reference holds the `cameraFocalPoint`. In this scenario, the annotation data is generated from [here](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-sr/src/utils/hydrateStructuredReport.ts#L186-L194).


https://github.com/user-attachments/assets/8e047066-fc85-4dcb-bdbf-2a033b267deb

**Comment by sedghi** [comment]
I fixed the camera focal point yesterday in cornerstone https://github.com/cornerstonejs/cornerstone3D/pull/1950 let me see what is going on

**Comment by sedghi** [comment]
It works locally for me! maybe it is some weird netlify cache. Try locally

**Comment by arul-trenser** [comment]
@sedghi  Checked locally, issues got fixed
Thanks!

**Comment by sedghi** [comment]
I merged by mistake and reverted after FYI
