### PR TITLE
[OHI-798] fix(tools): enable additional tools in volume viewport

### LINKED ISSUE #4260: [Bug] Tools disabled with different layout
### Describe the Bug

Hello, some tools are disabled when I change the layout, even if I have selected the same view as before.

These are screenshots from Basic Viewer version 3.8.1. [link here](https://viewer.ohif.org/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2). In the first screenshot, there is only one view, and Freehand ROI, Splinewire ROI, and Calibration are available. When I press the layout button, select the 3D primary layout, and select the same view, these tools are not available (second screenshot).

Screenshot 2024-06-25 at 08 59 05

Screenshot 2024-06-25 at 09 00 15

### Steps to Reproduce

1. Open basic viewer
2. Check if Splinewire ROI and Livewire ROI tools are available
3. Change layout (any from advanced presets) 
4. Select same view 
5. Check the tools again

### The current behavior

Freehand ROI, Splinewire ROI and Calibration tools are not available, when advanced layout is used.

### The expected behavior

Tools should be available when I am working with same view, it should not be dependant on layout

### OS

OS X 10.15.7

### Node version

20.6.1

### Browser

Safari 17.2.1, Chrome 126.0.0

### PR DESCRIPTION
**Pull request by IbrahimCSAE**
### Context

Enables some tools that were disabled for volume viewports.

Fixes OHI-798
Fixes #4260

fixes https://github.com/OHIF/Viewers/issues/4538 by upgrading cornerstone

### CODE REVIEW

File: modes/longitudinal/src/initToolGroups.js [hunk 1]
```diff
@@ -243,6 +243,9 @@ function initMPRToolGroup(extensionManager, toolGroupService, commandsManager, m
       { toolName: toolNames.Angle },
       { toolName: toolNames.CobbAngle },
       { toolName: toolNames.PlanarFreehandROI },
+      { toolName: toolNames.SplineROI },
+      { toolName: toolNames.LivewireContour },
+      { toolName: toolNames.CalibrationLine },
```
Comment (sedghi) [inline modes/longitudinal/src/initToolGroups.js:248]: i don't think calibration is used (works) in volume, maybe take this out. Also see if any other mode need to be edited by adding spline and livewire

**Review by sedghi — APPROVED** [review]
