### PR TITLE
fix(hotkeys): preserve hotkeys if changed, and reduce re-rendering

### LINKED ISSUE #3598: [Bug] User preference hotkeys not reloaded from local storage
### Describe the Bug

You can change hotkeys and save them, and they persist for the duration of the tab. However, on refresh (and likely on going from one Mode to another) the hotkeys get reset to default.

I think the problem is [here](https://github.com/OHIF/Viewers/blob/daf734e09e843f5474301124aab0429289436878/platform/app/src/routes/Mode/Mode.tsx#L173).

The change was good, insofar as if you add a hotkey object to a Mode, it will use the name member to set and retrieve the hotkeys. However, the default behaviour is to _write_ the hotkeys to 'hotkey-definitions', but read them from 'hotkey-definitions-v2'.

Fixed locally by changing above line to the expected 'hotkey-definitions'. 

@wayfarer3130 made the change, and may be able to add more context.

### Steps to Reproduce

1. Go to a [viewer](https://viewer.ohif.org/).
2. Open any BasicViewer.
3. Change a hotkey in Preferences.
4. Save.
5. Reload the page.
6. Note the hotkeys are back to defaults.

### The current behavior

No hotkeys are restored from LS.

### The expected behavior

User preference hotkeys are restored from LS.

### OS

Windows 10

### Node version

16.15.0-slim

### Browser

Chrome 115.0.5790.110

### PR DESCRIPTION
**Pull request by sedghi**
### Context

fixes #3598 

Hotkeys were not getting restored after refresh. 

There were too many re-renderings happening because of modals and useTranslation

### Changes & Results

Fixes the re-renderings as shown below by refactoring and not changing language if the same

Current behaviour 

https://github.com/OHIF/Viewers/assets/7490180/864562db-997d-4178-9a08-dd657a976edd

After this PR
- No re-rendering -> No `search for studies` 

### Testing

- Changed hotkeys in the user preferences should be preserved after refresh
- the app should feel faster after save preferences (since there is no re-renderings)

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: platform/app/src/routes/Mode/Mode.tsx [hunk 1]
```diff
@@ -164,7 +164,7 @@ export default function ModeRoute({
 
   // Preserve the old array interface for hotkeys
   const hotkeys = Array.isArray(hotkeyObj) ? hotkeyObj : hotkeyObj?.hotkeys;
-  const hotkeyName = hotkeyObj?.name || 'hotkey-definitions-v2';
+  const hotkeyName = hotkeyObj?.name || 'hotkey-definitions';
```
Comment (jbocce) [inline platform/app/src/routes/Mode/Mode.tsx:167]: Does this affect anyone migrating from v2?

Comment (sedghi) [reply platform/app/src/routes/Mode/Mode.tsx:167]: I don't think that was supposed to be v2, prob just a typo

**Review by jbocce — APPROVED** [review]

**Comment by jbocce** [comment]
Looks great. Great catch on the rerendering!
