### PR TITLE
[OHI-1445] fix(store-segmentation): storing segmentations was hitting the wrong command resulting in an undefined datasource

### LINKED ISSUE #4584: [Bug] Export DICOM SEG will fail at storeSegmentation
### Describe the Bug

I can draw seg.

But it throws the bug when I export the seg.

Even I use the DICOM study provided by OHIF or myself on localhost , it occurs the same.

```
Context: Route /segmentation

Error Message: Cannot read properties of undefined (reading 'store')

Stack: TypeError: Cannot read properties of undefined (reading 'store')
at storeSegmentation (http://localhost:3005/extensions_cornerstone-dicom-seg_src_index_tsx.js:267:24)
```

Image

In addition , I noticed some warning when I `git clone & yarn install & yarn start`. 
Not sure if it is related or not

Image

Image

### Steps to Reproduce

1. Checkout the `master` branch or tag `v3.9.1`
2. Visit the anonymous study provided by OHIF
Or directly visit localhost : http://localhost/segmentation?StudyInstanceUIDs=1.2.826.0.1.3680043.2.1125.1.11608962641993666019702920539307840    
Or directly visit ohif-online-example : 
https://viewer.ohif.org/segmentation?StudyInstanceUIDs=1.2.826.0.1.3680043.2.1125.1.11608962641993666019702920539307840

Image

3. Draw the seg and click export button , will throw the bug
Image

### The current behavior

```
Context: Route /segmentation

Error Message: Cannot read properties of undefined (reading 'store')

Stack: TypeError: Cannot read properties of undefined (reading 'store')
at storeSegmentation (http://localhost:3005/extensions_cornerstone-dicom-seg_src_index_tsx.js:267:24)
```

Image

### The expected behavior

The DICOM SEG should be exported successfully.

### OS

macOS 14.4.1

### Node version

v18.20.0

### Browser

Chrome

### PR DESCRIPTION
**Pull request by IbrahimCSAE**
### Context

In segmentation mode, exporting a segmentation would incorrectly prioritize the `storeSegmentation` command from the `cornerstone-dicom-seg` extension instead of first invoking the regular `cornerstone` extension command to retrieve the data source before passing it to the second command.

This behavior occurred because `storeSegmentation` exists in both modules, causing it to default to `cornerstone-dicom-seg` first. Other commands did not face this issue since they do not exist in `cornerstone-dicom-seg`, allowing them to fall back to `cornerstone` as expected. 

This has been resolved by explicitly passing the `CORNERSTONE` context name to ensure the correct command execution order.

CleanShot 2025-01-31 at 10 55 17

Fixes #4584 
Fixes OHI-1445

### CODE REVIEW

File: extensions/default/src/Components/MoreDropdownMenu.tsx [hunk 1]
```diff
@@ -12,16 +12,36 @@ import {
...
+    item,
+  }: {
+    item: {
+      id: string;
+      label: string;
+      iconName: string;
+      onClick: ({ servicesManager, commandsManager, ...props }: withAppTypes) => () => void;
+    };
+  }) => (
+    <DropdownMenuItem onClick={() => item.onClick({ ...props })}>
```
Comment (IbrahimCSAE) [inline extensions/default/src/Components/MoreDropdownMenu.tsx:39]: passing {...props} will let anyone pass whatever their `onClick` needs, example:

```
              <ThumbnailMenuItems
                displaySetInstanceUID={displaySetInstanceUID}
                canReject={canReject}
                onReject={onReject}
              />
              
```

File: extensions/default/src/customizations/studyBrowserCustomization.ts [hunk 2]
```diff
@@ -8,7 +8,11 @@ export default {
       id: 'tagBrowser',
       label: 'Tag Browser',
       iconName: 'DicomTagBrowser',
-      commands: 'openDICOMTagViewer',
+      onClick: ({ servicesManager, commandsManager, displaySetInstanceUID }: withAppTypes) => {
+        commandsManager.runCommand('openDICOMTagViewer', {
```
Comment (sedghi) [inline extensions/default/src/customizations/studyBrowserCustomization.ts:12]: i guess you don't need servicesManager

File: extensions/default/src/Components/MoreDropdownMenu.tsx [hunk 3]
```diff
@@ -12,16 +12,36 @@ import {
...
+    item: {
+      id: string;
+      label: string;
+      iconName: string;
+      onClick: ({ ...props }: withAppTypes) => () => void;
+    };
+  }) => (
+    <DropdownMenuItem onClick={() => item.onClick({ ...props })}>
+      <div className="flex items-center gap-2">
+        <Icons.ByName name={item.iconName} />
```
Comment (sedghi) [inline extensions/default/src/Components/MoreDropdownMenu.tsx:41]: Should check if item has iconNamme before this

**Review by sedghi — COMMENTED** [review]
better now

**Review by sedghi — APPROVED** [review]
