### PR TITLE
fix(ui-next): Add validation for opacity and border inputs in the segmentation panel - OHIF-2332

### LINKED ISSUE #5591: [Bug] No limit on textboxes on opacity and border for segmentation
### Describe the Bug

The text box for the sliders next to opacity and border have no limit to the number they can enter. e.g. they can enter in 3000000 or !!. No error is displayed for anything invalid

Image

Image

### Steps to Reproduce

1. Open a study in segmentation and add a segment 
2. Enter anything in the text boxes for opacity and border e.g. !, 30000000, 99, 1 

### The current behavior

- Anything is accepted. 
- No errors displayed for invalid input

### The expected behavior

- A limit is placed on what the user can enter - maybe this is in terms of number of digits? 
- If invalid input is entered, a error should be displayed or the user is blocked from entering this and the text box is not updated with the content

### System Information

  System:
    OS: Windows 11 10.0.26100
    CPU: (14) x64 Intel(R) Core(TM) Ultra 7 265U
    Memory: 4.34 GB / 31.46 GB
  Browsers:
    Chrome: 142.0.7444.176

### PR DESCRIPTION
**Pull request by GhadeerAlbattarni**
### Context

Fixes #5591 

The opacity and border input fields in the segmentation panel (right side panel) were accepting any text or numeric value without validation. So this PR fixes this issue. 

### Changes 
Replaced manual `Slider` + `Input` components with `Numeric.Container` component which provides:
- Automatic value clamping (0-1 for opacity, 0-10 for border)
- Invalid input rejection (NaN values are ignored)

### Results
  Values are now automatically validated and the user can no longer enter a text or a number out of range. 

### Testing

1. Open a study in a segmentation mode
2. Add a segmentation in the right panel 
3. Test opacity slider: verify it works from 0 to 1
4. Test opacity text: 
- Enter valid values (0, 0.5, 1) - should accept
- Enter out-of-range values (5, 3000000) - should clamp to max/min
- Enter invalid characters (e.g. abc) - should be ignored
5. Test border slider: verify it works from 0 to 10
- Test border text input with same validation scenarios

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: macOS 10.15.4
- [] Node version: v22.12.0
- [] Browser: Chrome 83.0.4103.116

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

<h2>Greptile Overview</h2>

<h3>Greptile Summary</h3>

Replaced manual input validation with the `Numeric.Container` component for opacity and border controls in the segmentation panel. The `Numeric.Container` component automatically handles input validation, clamping values to specified ranges (0-1 for opacity, 0-10 for border), and rejecting invalid input (NaN values are ignored). This refactoring eliminates the previous issue where users could enter arbitrary text or out-of-range numeric values.

**Changes:**
- Removed manual `Slider` and `Input` components
- Integrated `Numeric.Container` with `Numeric.SingleRange` for three input fields: active opacity, border width, and inactive opacity
- Values are now automatically clamped within their valid ranges
- Invalid text input is properly ignored rather than causing errors

<h3>Confidence Score: 5/5</h3>

- This PR is safe to merge with minimal risk
- The change is a straightforward refactoring that replaces manual input handling with a well-tested component (`Numeric.Container`) already used throughout the codebase. The component provides proper validation and clamping logic, eliminating the security concern of unvalidated user input. No new functionality is introduced, only improved input validation for existing controls.
- No files require special attention

<details><summary><h3>Important Files Changed</h3></summary>

| Filename | Overview |
|----------|----------|
| platform/ui-next/src/components/SegmentationTable/SegmentationTableConfig.tsx | Replaced manual `Slider` + `Input` with `Numeric.Container` for opacity (0-1) and border (0-10) inputs, providing automatic validation and clamping |

</details>

</details>

<sub>Last reviewed commit: f9367b3</sub>

### CODE REVIEW

File: platform/ui-next/src/components/SegmentationTable/SegmentationTable.tsx [hunk 1]
```diff
@@ -120,7 +120,10 @@ export const SegmentationTableRoot = (props: SegmentationTableProps) => {
         <PanelSection.Header className="flex items-center justify-between">
           <span>{t(title)}</span>
           {hasConfigComponent && (
-            <div className="ml-auto mr-2">
+            <div
+              className="ml-auto mr-2"
+              data-cy="segmentation-config-toggle"
```
Comment (jbocce) [inline platform/ui-next/src/components/SegmentationTable/SegmentationTable.tsx]: Thank you for this. However I think we should add the `segmentationType` to the id. The `segmentationType`might be one of the component properties. Have a look.

Comment (jbocce) [reply platform/ui-next/src/components/SegmentationTable/SegmentationTable.tsx]: The reason for adding the type is for the case when BOTH the contour and the label map tabs are visible say when one is in the left panel and the other is in the right panel.

File: tests/pages/RightPanelPageObject.ts [hunk 2]
```diff
@@ -201,6 +201,51 @@ export class RightPanelPageObject {
           };
         },
       },
+
+      get config() {
```
Comment (jbocce) [inline tests/pages/RightPanelPageObject.ts:205]: This should likely/eventually be in both the label map and contour panels (above). But for now you can add it just to the one you are using in your test which I think is label map.

File: tests/pages/RightPanelPageObject.ts [hunk 3]
```diff
@@ -201,6 +201,51 @@ export class RightPanelPageObject {
...
+              input: container.locator('input'),
+              slider: container.getByRole('slider'),
+              fill: async (value: string) => {
+                await container.locator('input').fill(value);
+              },
+            };
+          },
+
+          get border() {
+            const container = page.getByTestId('segmentation-config-border');
```
Comment (jbocce) [inline tests/pages/RightPanelPageObject.ts]: I think we will need to change this id and the one below to include the segmentation type in the name.

File: tests/SegmentationPanel.spec.ts [hunk 4]
```diff
@@ -76,3 +76,130 @@ test('checks saved segmentations loads and jumps to slices', async ({
...
+      const { opacity } = rightPanelPageObject.labelMapSegmentationPanel.config;
+
+      await opacity.fill('-1');
+      await expect(opacity.input).toHaveValue('0');
+    });
+
+    test('should reject non-numeric opacity input', async ({ rightPanelPageObject }) => {
+      const { opacity } = rightPanelPageObject.labelMapSegmentationPanel.config;
+
+      await expect(opacity.fill('abc')).rejects.toThrow('Cannot type text into input[type=number]');
```
Comment (jbocce) [inline tests/SegmentationPanel.spec.ts]: The error text that is expected should be a constant.

File: platform/ui-next/src/components/SegmentationTable/SegmentationTable.tsx [hunk 5]
```diff
@@ -122,7 +124,7 @@ export const SegmentationTableRoot = (props: SegmentationTableProps) => {
           {hasConfigComponent && (
             <div
               className="ml-auto mr-2"
-              data-cy="segmentation-config-toggle"
+              data-cy={`segmentation-config-toggle-${segmentationRepresentationTypes?.[0]}`}
```
Comment (jbocce) [inline platform/ui-next/src/components/SegmentationTable/SegmentationTable.tsx]: Unfortunately, this will not work well when `segmentationRepresentationTypes` is null. It is null when the panel has ALL segmentation types (i.e. label map and contour). In that case we don't want `segmentation-config-toggle-null` but just `segmentation-config-toggle`. So I think we need to decide what to show in a constant and concatenate the constant here. So something like this...

```
const dataCySuffix = segmentationRepresentationTypes ? `-${segmentationRepresentationTypes[0]}` : '';

. . . 

<div
   className="ml-auto mr-2"
   data-cy={`segmentation-config-toggle-${dataCySuffix}`}
```

File: platform/ui-next/src/components/SegmentationTable/SegmentationTableConfig.tsx [hunk 6]
```diff
@@ -88,7 +88,7 @@ export const SegmentationTableConfig: React.FC<{ children?: React.ReactNode }> =
           </Label>
           <div
             className="mx-1 flex-1"
-            data-cy="segmentation-config-opacity"
+            data-cy={`segmentation-config-opacity-${segmentationRepresentationTypes?.[0]}`}
```
Comment (jbocce) [inline platform/ui-next/src/components/SegmentationTable/SegmentationTableConfig.tsx]: See previous comment concerning this.

File: tests/SegmentationPanel.spec.ts [hunk 7]
```diff
@@ -76,3 +76,134 @@ test('checks saved segmentations loads and jumps to slices', async ({
...
+      const { opacity } = rightPanelPageObject.labelMapSegmentationPanel.config;
+
+      await opacity.fill('-1');
+      await expect(opacity.input).toHaveValue('0');
+    });
+
+    test('should reject non-numeric opacity input', async ({ rightPanelPageObject }) => {
+      const { opacity } = rightPanelPageObject.labelMapSegmentationPanel.config;
+
+      const nonNumericError = 'Cannot type text into input[type=number]';
```
Comment (jbocce) [inline tests/SegmentationPanel.spec.ts]: Declare this once at the top of the file so that there is only ONE place to edit it if we ever have to.

**Comment by GhadeerAlbattarni** [comment]
Thanks for your review!
