### PR TITLE
fix: seg sync for data without FOR

### LINKED ISSUE #5564: [Bug] Segmentation synchronization fails between viewports in advanced layout for data without a FrameOfReferenceUID
### Describe the Bug

Segmentation synchronization breaks in Advanced Layout for datasets that are missing a FrameOfReferenceUID. When a segmentation is drawn in one viewport (e.g., axial), it is not reflected in the other viewports (coronal, sagittal, or 3D).

### Steps to Reproduce

1. Load a data that does not include FrameOfReferenceUID in its DICOM metadata.
2. Switch to Advanced Layout (multi-viewport mode).
3. Draw a segmentation in any one of the viewports.
4. Observe that the segmentation does not appear in the other viewports.

### The current behavior

Segmentation appears only in the viewport where it was drawn and not syncing with other viewports

### The expected behavior

Segmentation should sync among axial, coronal, and sagittal viewports

### System Information

System:
OS: Linux 6.11 Ubuntu 24.10 24.10 (Oracular Oriole)
Node: 22.16.0 - ~/.nvm/versions/node/v22.16.0/bin/node
Chrome: 139.0.7258.154

### PR DESCRIPTION
**Pull request by Devu-trenser**
### Context
This PR fixes a synchronization issue where segmentation drawn in one viewport does not sync to the other viewports (axial, coronal, sagittal) when the dataset is missing a FrameOfReferenceUID.

Fixes: https://github.com/OHIF/Viewers/issues/5564
This PR is incorporated by [FlyWheel.io](https://flywheel.io/)
Segmentation should propagate across all viewports in advanced layout regardless of whether FrameOfReferenceUID is present.

### Changes & Results
Modification include to sync segmentation representation among viewport based on the check whether the source and target viewport share a DisplaySet in common.

Before:

https://github.com/user-attachments/assets/ed63b609-97ec-4ff1-8d12-74fe30a0b632

After:

https://github.com/user-attachments/assets/4200a6b7-ac80-48b4-8437-e139102ffa42

### Testing

- Load a dataset without FrameOfReferenceUID. Test data: https://drive.google.com/file/d/1zweFqrz-lCBYUlvRd9ZflPcGdIyYT0mP/view?usp=sharing
- Switch to Advanced Layout (multi-viewport).
- Draw a segmentation in one viewport.
- Confirm that the segmentation appears in all other viewports (axial, coronal, sagittal).

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS:  Linux 6.11 Ubuntu 24.10 24.10 (Oracular Oriole)
- [x] Node version:  22.16.0
- [x] Browser: 139.0.7258.154
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by Devu-trenser** [comment]
@wayfarer3130 Could you please review this PR when you get a chance?

**Comment by wayfarer3130** [comment]
@Devu-trenser - is there a specific study to test with?  I know I've seen non-FOR studies, I just don't know which ones they are off hand.

**Comment by wayfarer3130** [comment]
I'm also going to use the same study to test save/restore functionality using the updated save functionality and the same for RT.

**Comment by wayfarer3130** [comment]
The study uid 1.3.6.1.4.1.9590.100.1.2.258919851312376095531363851672952828556 works for this.

**Review by wayfarer3130 — COMMENTED** [review]
I've tried this on an example study load and it doesn't seem to affect the outcome either way.  Maybe an example from viewer-dev would help?

**Comment by Devu-trenser** [comment]
@wayfarer3130 The data was obtained from the following source:
https://drive.google.com/file/d/0ByBLJ2-U1t9xRGtZRXVtazBMWXM/view?resourcekey=0-WETlslbx8cpV-5Uo3bg6RQ from https://www.aliza-dicom-viewer.com/download/datasets.

The Frame of Reference UID was removed from the series, and used the modified dataset for the current testing.
Modified data: https://drive.google.com/file/d/1zweFqrz-lCBYUlvRd9ZflPcGdIyYT0mP/view

A before-and-after comparison video has been included in the Changes & Results section for reference.

**Comment by Devu-trenser** [comment]
@wayfarer3130  We have added the sample test data and rebased to the latest master branch. It also appears that the vulnerability issue has been resolved as part of the rebase. When you have a moment, could you please review this PR?

File: extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts [hunk 1]
```diff
@@ -44,15 +44,28 @@ const segmentationRepresentationModifiedCallback = async (
...
-  const targetFrameOfReferenceUID = viewport.getFrameOfReferenceUID();
+  const sourceDisplaySetUIDs = sourceViewportInfo
+    .getViewportData()
+    .data.map(ds => ds.displaySetInstanceUID);
+  const targetDisplaySetUIDs = targetViewportInfo
+    .getViewportData()
+    .data.map(ds => ds.displaySetInstanceUID);
 
-  if (!targetFrameOfReferenceUID) {
+  // Check if any displaySet is shared between source and target.
```
Comment (wayfarer3130) [inline extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts]: Can you extract a method isAnyDisplaySetCommon or something like that which you can add your documentation to?  That allows you to have common documentation on what the method does rather than trying to include code level comments that don't get exported/seen.  You can add that as a general utility so it is findable by others as I suspect it will be needed in the future.

That method needs to have a comment like:

This method checks to see if the source and target share a display set.  This is a `O(n * m)` operation on the number of display sets in each viewport, but since this is expected to be small (<=5), the cost for this check is quite low.

File: extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts [hunk 2]
```diff
@@ -44,15 +44,28 @@ const segmentationRepresentationModifiedCallback = async (
   const event = sourceEvent as ToolsTypes.EventTypes.SegmentationRepresentationModifiedEventType;
 
   const { segmentationId, type: segmentationRepresentationType } = event.detail;
-  const { segmentationService } = servicesManager.services;
+  const { segmentationService, cornerstoneViewportService } = servicesManager.services;
```
Comment (wayfarer3130) [inline extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts:55]: Can you add a general comment to segmentationRepresentationModifiedCallback saying that:
This method will add the segmentation representation to any viewports having:

- the same FOR as the segmentation representation
- sharing a display set with the source viewport when there is no FOR

@igoroctaviano - note this bit of code is being added.  When the flag gets added to control whether the 
segmentations are displayed by FOR or not, this code will need to get updated.

@Devu-trenser - at some point there are goign to be changes to allow controlling how segmentation is handled so that there are several options:
1. Display any seg on the same FOR
2. Display any seg having a shared display set (the change you are making here)
3. Filter seg display by some criteria such as a grouped name for the seg to allow viewports/hanging protocols to define specific sets of segs to display

File: extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts
Comment (wayfarer3130) [inline extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts:1]: Can you add the comment generally on the top level function around what it does?  Also, if any const function is separable, that is can be declared as it's own function, could you extract it?  Declaring private functions within a block is generally not a good idea unless they are specifically using the overall context.

File: extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts (hunk 1 above)
Comment (Devu-trenser) [reply extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts]: @wayfarer3130  Sure! I’ve extracted the logic into a new isAnyDisplaySetCommon utility and added the documentation you suggested, including the note about the O(n * m) lookup cost. Let me know if you'd like it placed somewhere else.

File: extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts (hunk 2 above)
Comment (Devu-trenser) [reply extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts:55]: Done! I’ve added a general comment to segmentationRepresentationModifiedCallback.

File: extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts
Comment (Devu-trenser) [reply extensions/cornerstone/src/services/SyncGroupService/createHydrateSegmentationSynchronizer.ts:1]: I have updated it.

**Review by wayfarer3130 — APPROVED** [review]

**Comment by sen-trenser** [comment]
@wayfarer3130 It seems the license compliance failed check is also failed for other PRs that were merged, and we cannot see the issue report. 
If this is not blocking, could you please help to merge this?
Thanks!
