### PR TITLE
fix(context menu): Context menus for edge-proximate measurements are partially obscured.

### LINKED ISSUE #4726: [Bug] Context menu is not fully visible for the measurements which is near the viewport border.
### Describe the Bug

The context menu for the measurement is not fully visible if the measurement is drawn at the edges of the viewport

### Steps to Reproduce

1. Launch a study
2. Drawn an annotation at the edge of the viewport
3. Right click on the measurement the context menu is not fully visible

### The current behavior

https://github.com/user-attachments/assets/73e32ef8-6b46-4370-9b10-eedc58567ff2

### The expected behavior

https://github.com/user-attachments/assets/b017ea93-4896-462d-be92-8df995790040

### OS

Window 11

### Node version

18.19.0

### Browser

Chrome 131.0.6778.265

### PR DESCRIPTION
**Pull request by arul-trenser**
### Context
The issue that context menu is not fully visible near the edges of the viewport has be incorporated by [FlyWheel.io](https://flywheel.io/).
Closes #4726 

### Changes & Results
The context menu for edge-proximate measurements experiences clipping. A solution involves dynamically calculating the menu's position relative to the window's inner height and width to ensure full visibility.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS: Windows 11
- [x] Node version:  18.19.0
- [x] Browser: Chrome 131.0.6778.265
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: platform/ui/src/components/ContextMenu/ContextMenu.tsx [hunk 1]
```diff
@@ -7,8 +7,25 @@ const ContextMenu = ({ items, ...props }) => {
...
+      props.defaultPosition.y = props.defaultPosition.y - boundingClientRect.height;
+    }
+    if (boundingClientRect.right + boundingClientRect.width > window.innerWidth) {
+      props.defaultPosition.x = props.defaultPosition.x - boundingClientRect.width;
+    }
+  }, [props.defaultPosition]);
+
   return (
     <div
+      id="context-menu"
```
Comment (sedghi) [inline platform/ui/src/components/ContextMenu/ContextMenu.tsx:28]: how about a useRef?

Comment (arul-trenser) [reply platform/ui/src/components/ContextMenu/ContextMenu.tsx]: @sedghi I've refactored the code with useRef hook.

**Review by sedghi — APPROVED** [review]
Thanks! In the future (not now), let's move to TypeScript types and interfaces instead of editing the PropTypes, as that is the direction we are moving forward.
