### PR TITLE
fix: prevent viewer crash when opening DICOM Tag Browser from empty viewport - OHIF-2351

### LINKED ISSUE #5623: [Bug] OHIF crashes if opening the DICOM Tags Browser in a stage that does not display any display set
### Describe the Bug

If a stage has no display set to show because of non matching series rules, opening the dicom tag browser makes ohif crashing

see video

https://github.com/user-attachments/assets/d0c0ab53-0b63-4c32-b533-ba5a85bd3601

### Steps to Reproduce

Open a stage with no mathing display set
Open the tag browser

### The current behavior

Ohif crashes because of an uncaught error

### The expected behavior

Dicom tag browser shall open normally

### System Information

Chrome latest

### PR DESCRIPTION
**Pull request by GhadeerAlbattarni**
### Context

Fixes #5623 

When using a multi-viewport layout and the **active viewport has no display set**, opening the **DICOM Tag Browser** caused the viewer to **crash**. The code was passing `undefined` as `displaySetInstanceUID` into the DICOM Tag Browser, which led to the error.

### Changes & Results

In default extension `commandsModule`, the default `defaultDisplaySetInstanceUID` is now computed with a three-level fallback:
- `displaySetInstanceUID` (if explicitly provided by the caller), else
- `displaySetInstanceUIDs[0]` (active viewport's first display set), else
- `displaySets[0].displaySetInstanceUID` (first loaded display set in the study)

So when the active viewport has no display set, the DICOM Tag Browser opens with the first series instead of crashing.

### Testing
1. Open a study (e.g. one series).
2. Change layout to 3×3 
3. click on a viewport that has no `displayset` 
4. Open DICOM Tag Browser from the toolbar.
5. Verify :
- The viewer does not crash.
- The DICOM Tag Browser opens.
- The series selector shows the first (default) series in the study.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS: macOS 10.15.4
- [x] Node version: v22.12.0
- [x] Browser: Chrome 83.0.4103.116

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

<h3>Greptile Summary</h3>

Fixed crash when opening DICOM Tag Browser from empty viewport by adding third fallback to use first available display set in study.

- Added fallback logic: `displaySetInstanceUID || displaySetInstanceUIDs[0] || displaySets[0].displaySetInstanceUID`
- Added tests for both empty viewport and viewport with display set scenarios
- Refactored test page object to extract `getOptionLabel` helper method

**Issue found:** The new fallback `displaySets[0].displaySetInstanceUID` will crash if `displaySets` is empty (e.g., on mode exit or when no data is loaded). Use optional chaining: `displaySets[0]?.displaySetInstanceUID`

<h3>Confidence Score: 3/5</h3>

- This PR fixes the original crash but introduces a potential new crash scenario
- The fix addresses the immediate issue of empty viewports, and tests cover the main scenarios. However, the unsafe array access `displaySets[0].displaySetInstanceUID` without optional chaining could crash if the `displaySets` array is empty (which can happen on mode exit or when no data is loaded)
- Pay close attention to `extensions/default/src/commandsModule.ts` line 660 - requires optional chaining to prevent potential crash

<details><summary><h3>Important Files Changed</h3></summary>

| Filename | Overview |
|----------|----------|
| extensions/default/src/commandsModule.ts | Added third fallback to prevent crash when viewport has no display set, but unsafe array access could still crash if `displaySets` is empty |
| tests/DicomTagBrowser.spec.ts | Added comprehensive tests for empty viewport scenario and viewport with display set, good coverage of the bug fix |
| tests/pages/DicomTagBrowserPageObject.ts | Refactored `selectOption` to extract `getOptionLabel` helper method for reusability in tests |

</details>

</details>

<h3>Flowchart</h3>

```mermaid
%%{init: {'theme': 'neutral'}}%%
flowchart TD
    A[Open DICOM Tag Browser] --> B{displaySetInstanceUID<br/>provided?}
    B -->|Yes| Z[Use provided UID]
    B -->|No| C{Active viewport has<br/>display set?}
    C -->|Yes| D[Use displaySetInstanceUIDs first item]
    C -->|No| E{displaySets array<br/>has items?}
    E -->|Yes| F[Use displaySets first item UID]
    E -->|No| G[CRASH: Array access error]
    D --> H[Show Tag Browser]
    Z --> H
    F --> H
    G --> I[Error thrown]
    
    style G fill:#ff6b6b
    style I fill:#ff6b6b
    style H fill:#51cf66
```

<sub>Last reviewed commit: 1d8edbe</sub>

### CODE REVIEW

File: tests/pages/DicomTagBrowserPageObject.ts [hunk 1]
```diff
@@ -29,13 +29,16 @@ export class DicomTagBrowserPageObject {
...
-      async selectOption(index) {
+      async getOptionLabel(index) {
         await this.click();
         const optionText = await options.nth(index).innerText();
-        const selectedText = optionText.split('\n')[0].trim();
+        const optionLabel = optionText.split('\n')[0].trim();
+        return optionLabel;
+      },
 
+      async selectOption(index) {
```
Comment (jbocce) [inline tests/pages/DicomTagBrowserPageObject.ts:39]: Nice refactoring. Well done!

File: tests/pages/DicomTagBrowserPageObject.ts [hunk 2]
```diff
@@ -29,13 +29,16 @@ export class DicomTagBrowserPageObject {
         await trigger.click();
       },
 
-      async selectOption(index) {
+      async getOptionLabel(index) {
```
Comment (jbocce) [inline tests/pages/DicomTagBrowserPageObject.ts]: I think `getOptionText` is a better name.

File: tests/pages/DicomTagBrowserPageObject.ts [hunk 3]
```diff
@@ -29,13 +29,16 @@ export class DicomTagBrowserPageObject {
...
         await this.click();
         const optionText = await options.nth(index).innerText();
-        const selectedText = optionText.split('\n')[0].trim();
+        const optionLabel = optionText.split('\n')[0].trim();
```
Comment (jbocce) [inline tests/pages/DicomTagBrowserPageObject.ts]: How about `trimmedOptionText` instead?

**Comment by GhadeerAlbattarni** [comment]
Thanks for your comments!
