### PR TITLE
fix(microscopy): rename measurement in microscopy mode

### LINKED ISSUE #5797: [Bug] Rename measurement in microscopy doesn't work
### Describe the Bug

see title.

### Steps to Reproduce

1. Display a study in microscopy .e.g https://viewer-dev.ohif.org/microscopy?StudyInstanceUIDs=1.2.276.0.7230010.3.1.2.296485376.1.1665793212.499772
2. Add a measurement 
3. On the measurement panel select Rename. Enter in text and save 

https://github.com/user-attachments/assets/b63cd000-8f0c-4e18-8aab-0488e59f00c0

### The current behavior

Measurement still says empty

### The expected behavior

Measurement is renamed successfully or rename is not available if it's not supported in this mode.

### System Information

  System:
    OS: Windows 11 10.0.26100
    CPU: (14) x64 Intel(R) Core(TM) Ultra 7 265U
    Memory: 7.62 GB / 31.46 GB
  Browsers:
    Chrome: 144.0.7559.133
    Edge: Chromium (140.0.3485.54)

### PR DESCRIPTION
**Pull request by GhadeerAlbattarni**
### Context

Fixes #5797

When the user adds a measurement in microscopy mode, then clicks on rename, it's not working. This PR fixes this issue. 

### Changes & Results
Updated the `setLabel` in `getCommandsModule.ts` to: 
- Use `async/await` with the current promise-based `callInputDialog` API
- Pre-fill the dialog with the annotation's existing label 

https://github.com/user-attachments/assets/fb13cd21-d14c-4b87-a3f6-dc700adfcb37

### Testing
1. Open a study in microscopy mode
2. Draw any annotation 
3. In the right panel, click on `...` then click on rename 
4. Enter a new label and click Save
5. Verify the label updates in the panel
6. Reopen the dialog and verify the current label is pre-filled
7. Click Cancel and verify the label does not change

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] OS: macOS 10.15.4
- [x] Node version: v22.12.0
- [x] Browser: Chrome 83.0.4103.116

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

<h3>Greptile Summary</h3>

Fixed the rename measurement functionality in microscopy mode by converting the `setLabel` command from callback-based to async/await and pre-filling the input dialog with the annotation's existing label.

**Key changes:**
- Made `setLabel` function async and uses `await` with `callInputDialog`
- Changed `defaultValue` from empty string to `roiAnnotation.label ?? ''` to pre-fill existing label
- Added proper null/undefined check for the returned value before applying the label

**Issue found:**
- Missing null check for `roiAnnotation` before accessing its properties could cause runtime error if annotation doesn't exist

<h3>Confidence Score: 4/5</h3>

- Safe to merge with one defensive check recommended
- The fix properly addresses the reported issue by pre-filling the dialog and using async/await. However, missing a null check for `roiAnnotation` could cause a runtime error in edge cases.
- The `getCommandsModule.ts` file needs a defensive null check for `roiAnnotation` before accessing its properties

<details><summary><h3>Important Files Changed</h3></summary>

| Filename | Overview |
|----------|----------|
| extensions/dicom-microscopy/src/getCommandsModule.ts | Updated `setLabel` to use async/await and pre-fill dialog with existing label |

</details>

</details>

<sub>Last reviewed commit: 5fccd9d</sub>

### CODE REVIEW

File: extensions/dicom-microscopy/src/getCommandsModule.ts [hunk 1]
```diff
@@ -24,16 +24,20 @@ export default function getCommandsModule({
...
         uiDialogService,
-        defaultValue: '',
-        onSave: (value: string) => {
-          roiAnnotation.setLabel(value);
-          microscopyService.triggerRelabel(roiAnnotation);
-        },
+        defaultValue: roiAnnotation.label ?? '',
       });
+
+      if (value !== undefined && value !== null) {
```
Comment (jbocce) [inline extensions/dicom-microscopy/src/getCommandsModule.ts]: Do we do something similar for other, non-microscopy annotations if the value is null or undefined? Let's make sure and be consistent.

Also a more concise way to do the if is...
`if(value != null)`

However, what about is value is the empty string? In any case, let's first see what we do for other annotation renames.

File: tests/pages/MainToolbarPageObject.ts [hunk 2]
```diff
@@ -205,6 +204,17 @@ export class MainToolbarPageObject {
           },
         };
       },
+      get line() {
```
Comment (jbocce) [inline tests/pages/MainToolbarPageObject.ts:212]: Why is this so different than for the other tools? Why can't we do the following?

```
      get line() {
        const button = page.getByTestId('line');
        return {
          button,
          async click() {
            await measurementTools.click();
            await button.click();
          },
        };
      },
```

File: tests/MicroscopyPanel.spec.ts [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  const measurementRow = rightPanelPageObject.microscopyPanel.nthMeasurement(0);
+  await expect(measurementRow.locator).toBeVisible();
+
+  await expect(measurementRow.locator).toContainText('(empty)');
+
+  await measurementRow.actions.rename(newLabel);
+
+  await expect(DOMOverlayPageObject.dialog.input.locator).toBeHidden();
+
+  await expect(measurementRow.locator).toContainText(newLabel);
```
Comment (jbocce) [inline tests/MicroscopyPanel.spec.ts]: Maybe we should use toHaveText instead since we want it to be precisely the label.

**Comment by jbocce** [comment]
@hongxiao-gif here is another for you to test. Thank you so much ahead of time!

**Review by hongxiao-gif — COMMENTED** [review]
**Passed**
Testing steps:
1. Open a study in microscopy mode
2. Draw any annotation
2. In the right panel, click on ... then click on rename
3. Enter a new label and click Save
4. Verify the label updates in the panel
5. Reopen the dialog and verify the current label is pre-filled
6. Click Cancel and verify the label does not change

Testing environment:
 System:
    OS: Windows 11 10.0.26200
    CPU: (8) x64 Intel(R) Core(TM) Ultra 5 226V
    Memory: 4.34 GB / 15.67 GB
  Browsers:
    Chrome: 145.0.7632.117
    Edge: Chromium (144.0.3719.104)

https://github.com/user-attachments/assets/46664257-9f53-4f21-a499-349e43cf8099

File: extensions/dicom-microscopy/src/getCommandsModule.ts (hunk 1 above)
Comment (GhadeerAlbattarni) [reply extensions/dicom-microscopy/src/getCommandsModule.ts]: - Yes, in  `extensions/cornerstone/src/commandsModule.ts`, `handleMeasurementLabelDialog` uses same pattern. However looking at it again now, the current implementation can be even improved by adding `title` and `placeholder` similar to annotation. 

- When the value is an empty string, the value will set to default `(empty)` and it's same for other modes.

File: tests/pages/MainToolbarPageObject.ts (hunk 2 above)
Comment (GhadeerAlbattarni) [reply tests/pages/MainToolbarPageObject.ts:212]: `line` tool is the default active in `microscopy` mode, so when I tried to do same pattern with other tools, I got an error, because it rendered in two places and Playwright finds both elements, so it throws an error.

However the other tools in the `microscopy` could follow same pattern for other tools and I tested that.

Alternatively, I could use `selectedTool` in `measurementTools` instead and it would work as it's just clicking the default, but I thought it might be useful to explicit show what tool has been used.
