### PR TITLE
fix(segmentation): When setting the segmentation style and the representation type is not provided, apply the style to all representation types.

### LINKED ISSUE #5644: [Bug] Segmentation fill, outline, opacity and border width controls throw an exception in single panel segmentation mode
### Describe the Bug

After hydrating a segmentation in the basic viewer mode, the controls for adjusting the outline, opacity, fill and border widths throw an exception.

This is likely a regression caused by splitting the segmentation panel into two - one for contour and one for label map.

### Steps to Reproduce

1. View https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.32722.99.99.239341353911714368772597187099978969331
2. Open the side segmentation panel and attempt to alter the various settings.

### The current behavior

The following exception is thrown and no setting is applied.

```
Error: Unknown representation type: undefined
    at Object.getDefaultStyle (5400.bundle.5a07ce92ee04c066edbd.js:1:5946)
    at Object.getStyle (5400.bundle.5a07ce92ee04c066edbd.js:1:4557)
    at Object.setStyle (5400.bundle.5a07ce92ee04c066edbd.js:1:3007)
    at Module.y (7412.bundle.de73c323fff02c4238dc.js:1:93484)
    at Ja.setStyle (3081.bundle.6cb2886b8b3dcec30fb5.js:1:351982)
    at setRenderFillCommand (3081.bundle.6cb2886b8b3dcec30fb5.js:1:256034)
    at Be.runCommand (app.bundle.83b43d7b38ba1025564d.js:2:1091252)
    at Be.run (app.bundle.83b43d7b38ba1025564d.js:2:1091943)
    at setRenderFill (3081.bundle.6cb2886b8b3dcec30fb5.js:1:406917)
    at Object.onValueChange [as current] (app.bundle.83b43d7b38ba1025564d.js:2:2808350)
```

### The expected behavior

No exception thrown and settings applied appropriately.

### System Information

System:
OS: Windows 10 10.0.26200
CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
Memory: 6.84 GB / 31.68 GB
Binaries:
Node: 23.9.0 - ~\AppData\Local\fnm_multishells\52784_1765830696412\node.EXE
Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 10.9.2 - ~\AppData\Local\fnm_multishells\52784_1765830696412\npm.CMD
Browsers:
Edge: Spartan (20.9.0), Chromium (20.9.0), ChromiumDev (20.9.0)
Internet Explorer: 11.0.26100.7309
Chrome: 143.0.7499.110

### PR DESCRIPTION
**Pull request by jbocce**
### Context
Fixes #5644

### Changes & Results
When setting the segmentation style and the representation type is not provided, apply the style to all representation types.

### Testing
See #5644. Exceptions should no longer be thrown. Furthermore, for modes where there is a single segmentation panel those controls should apply to ALL segmentations regardless of type (since all segmentations are lumped together under one panel and are not divided by type).

Be sure to also test segmentation mode. The same controls there should behave as was described in #5563.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

  System:
    OS: Windows 11 10.0.26200
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 5.22 GB / 31.68 GB
  Binaries:
    Node: 20.9.0 - C:\Users\joebo\AppData\Local\fnm_multishells\588_1766028030924\node.EXE
    Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.1.0 - C:\Users\joebo\AppData\Local\fnm_multishells\588_1766028030924\npm.CMD
    bun: 1.2.23 - C:\Users\joebo\.bun\bin\bun.EXE
  Browsers:
    Chrome: 143.0.7499.110

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: extensions/cornerstone/src/commandsModule.ts [hunk 1]
```diff
@@ -1730,86 +1755,59 @@ function commandsModule({
...
-          { type: SegmentationRepresentations.Labelmap },
-          { fillAlphaInactive: value }
-        );
-        segmentationService.setStyle(
-          { type: SegmentationRepresentations.Contour },
-          { fillAlphaInactive: value }
-        );
-      }
-    },
+    setFillAlphaInactiveCommand: createSetStyleCommand('fillAlphaInactive'),
```
Comment (sedghi) [inline extensions/cornerstone/src/commandsModule.ts]: you can even do it at the bottom of the page where we create commands object, and remove all the implementation in the definitions
