### PR TITLE
[OHI-1538] fix(icons): icons missing for volume presets and others

### LINKED ISSUE #4652: [Bug] Missing Icons
### Describe the Bug

Rendering Presets - v3.10.0-beta.38
Search all
Missing Icon
CT-AAA
Missing Icon
CT-AAA2
Missing Icon
CT-Bone
Missing Icon
CT-Bones
Missing Icon
CT-Cardiac
Missing Icon
CT-Cardiac2
Missing Icon
CT-Cardiac3
Missing Icon
CT-Chest-Co...
Missing Icon
CT-Chest-Ve...
Missing Icon
CT-Coronary...
Missing Icon
CT-Coronary...
Missing Icon
CT-Coronary...
Missing Icon
CT-Cropped-...
Missing Icon
CT-Fat
Missing Icon
CT-Liver-Va...
Missing Icon
CT-Lung
Missing Icon
CT-MIP
Missing Icon
CT-Muscle
Missing Icon
CT-Pulmonar...
Missing Icon
CT-Soft-Tis...
Missing Icon
CT-Air
Missing Icon
MR-Angio
Missing Icon
MR-Default
Missing Icon
MR-MIP
Missing Icon
MR-T2-Brain
Missing Icon
DTI-FA-Brai...
Cancel

### Steps to Reproduce

3D-Rendering Presets-Missing Icon

### The current behavior

3D-Rendering Presets-Missing Icon

### The expected behavior

3D-Rendering Presets-Missing Icon

### OS

windows 10

### Node version

v20.x.x

### Browser

Chrome

### PR DESCRIPTION
**Pull request by IbrahimCSAE**
### Context

Fixes some icons that were not being display due to small name differences, or just being missing after the migration.

CleanShot 2025-01-09 at 23 52 04@2x

CleanShot 2025-01-09 at 23 52 34@2x

Closes #4652
Closes OHI-1538

### CODE REVIEW

File: extensions/cornerstone/src/components/WindowLevelActionMenu/VolumeRenderingPresetsContent.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ export function VolumeRenderingPresetsContent({
                 }}
               >
                 <Icons.ByName
-                  name={preset.name}
+                  name={preset.name.replace(/-/g, '')}
```
Comment (sedghi) [inline extensions/cornerstone/src/components/WindowLevelActionMenu/VolumeRenderingPresetsContent.tsx:65]: i prefer to change their name at the preset level

Comment (sedghi) [reply extensions/cornerstone/src/components/WindowLevelActionMenu/VolumeRenderingPresetsContent.tsx:65]: or change icon names actually that is better

**Review by sedghi — APPROVED** [review]
